name: Tock example

on:
  push:

jobs:
  build-and-sim:
    name: Build Tock app and simulate it on VeeR EL2
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v4
      - name: install deps
        run: |
          sudo apt update -qq
          sudo apt install -y --no-install-recommends git ccache dfu-util python3-dev python3-pip python3-setuptools python3-wheel python3-venv xz-utils file make gcc gcc-multilib g++-multilib curl automake autoconf libtool g++ coreutils policykit-1 uml-utilities dirmngr ca-certificates gnupg wget screen gcc-riscv64-unknown-elf unzip libbit-vector-perl \
          autotools-dev \
          bc bison build-essential \
          flex \
          gawk gperf \
          help2man \
          libexpat-dev libfl-dev libfl2 libgmp-dev \
          libmpc-dev libmpfr-dev libtool \
          ninja-build \
          patchutils python3 python3-pip \
          texinfo \
          zlib1g zlib1g-dev
          pip install meson
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"
          rustup install nightly-2024-01-01 --profile minimal
          git config --global url."https://github.com/".insteadOf "git@github.com:"
      - name: Setup submodules
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOCK_REPO_ACCESS_TOKEN }}
          submodules: recursive
      - name: Build and install Verilator
        run: |
          git clone https://github.com/verilator/verilator
          cd verilator
          git checkout v5.010
          autoconf
          ./configure
          make -j `nproc`
          sudo make install
          cd -
      - name: Build Tock app
        run: |
          ls -la
          source "$HOME/.cargo/env"
          cd tock/boards/veer_el2_sim
          make debug -j$(nproc)
          cd -
          riscv64-unknown-elf-objcopy -O verilog tock/target/riscv32imc-unknown-none-elf/debug/veer_el2_sim.elf kernel.hex
          cp tock/target/riscv32imc-unknown-none-elf/debug/veer_el2_sim.elf kernel.elf
          cd libtock-c
          git switch --detach d39bca6bec16bd61c905edd5492116b3e2a14ab6
          # XXX this mirror doesn't seem to work
          sed -i '/cs\.virginia\.edu/d' lib/fetch-newlib.sh
          sed -i '/cs\.virginia\.edu/d' lib/fetch-libc++.sh
          cd -
          # build test application
          cd app
          make TOCK_TARGETS='rv32imc|rv32imc.0x80030080.0x80070000|0x80030080|0x80070000' -j$(nproc)
          cd -
          cp app/build/rv32imc/rv32imc.0x80030080.0x80070000.tbf hello_world.tbf
          riscv64-unknown-elf-objcopy -I binary -O verilog hello_world.tbf hello_world.hex
          sed -i 's/@00000000/@80030000/g' hello_world.hex
          cat kernel.hex hello_world.hex > tock.hex
      - name: Simulate
        run: |
          cd cores-veer-el2
          export RV_ROOT=$(pwd)
          cp ../tock.hex program.hex
          sed -i 's/parameter MAX_CYCLES = 2_000_000;/parameter MAX_CYCLES = 10_000_000;/g' testbench/tb_top.sv
          make -C tools USER_MODE=1 verilator-build
          ./tools/obj_dir/Vtb_top
          mv exec.log ../tock.log

